### ISSUE TITLE
Applying the organization revenue threshold to government teams

### ISSUE THREAD

**Issue by konklone** [EFForg/dnt-policy#7]
The DNT policy currently says:

```
c. If the organization operating this domain has annual revenue of more than
   USD 25 million or €18 million in inflation-adjusted 2013 currency, it
   will conduct an annual audit of compliance with this policy.
```

This is a little tough for an organization like mine, [18F](https://18f.gsa.gov). We're a government team, not a for-profit company, and so "revenue" isn't really how we think of things. More than that, what our organization is -- 18F, GSA, the United States -- depends on how you look at it.

To me, it feels like our organization is 18F, and I personally don't think we're in a position to pay for an annual audit of compliance with this policy, were we to adopt it. 

How should we think about this policy, or what changes might be appropriate for government teams?

**Comment by pde** [comment]
Do you have any ideas about wording that might sensibly scope compliance to a particular unit of a larger organisation?  Perhaps that is acceptable if all non-anonymized data remains within that organizational unit?

**Comment by pde** [comment]
The change proposed in #15 would make this a moot point.  What do folks think of that alternative standard for auditing?

**Comment by konklone** [comment]
I agree that it would make this issue a moot point, and it looks good to me.
